# Generated by Django 4.0.4 on 2022-06-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_cliente', '0002_alter_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[('1', 'Consulta'), ('2', 'Reclamo'), ('3', 'Sugerencias'), ('4', 'Felicitaciones')]),
        ),
    ]
