# Generated by Django 4.0.4 on 2022-06-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_cliente', '0004_alter_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('idhrs_dispos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('detalle', models.CharField(max_length=45)),
                ('fec_creacion', models.DateTimeField()),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('horass', models.TimeField()),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
    ]
