# Generated by Django 4.0.4 on 2022-06-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_cliente', '0005_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('idhrs_disposr', models.AutoField(primary_key=True, serialize=False)),
                ('fechar', models.DateField()),
                ('horar', models.TimeField()),
                ('detaller', models.CharField(max_length=45)),
                ('fec_creacionr', models.DateTimeField()),
                ('precior', models.IntegerField(blank=True, null=True)),
                ('horassr', models.TimeField()),
            ],
            options={
                'db_table': 'tests',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
