# Generated by Django 4.0.3 on 2022-04-27 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_cli', models.CharField(max_length=45)),
                ('ap_cli', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_com', models.AutoField(primary_key=True, serialize=False)),
                ('nom_com', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emp', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_emp', models.CharField(max_length=45)),
                ('ap_emp', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=45)),
                ('sueldo', models.IntegerField()),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_esp', models.AutoField(db_column='id_Esp', primary_key=True, serialize=False)),
                ('nom_espe', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_esp', models.AutoField(db_column='id_Esp', primary_key=True, serialize=False)),
                ('nom_esp', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'especie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_gen', models.AutoField(db_column='id_Gen', primary_key=True, serialize=False)),
                ('nom_gen', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(db_column='id_Insumo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('inventario', models.IntegerField()),
            ],
            options={
                'db_table': 'insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_pac', models.AutoField(db_column='id_Pac', primary_key=True, serialize=False)),
                ('nom_pac', models.CharField(max_length=45)),
                ('fec_nac', models.DateField(blank=True, null=True)),
                ('raza', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.AutoField(db_column='idPago', primary_key=True, serialize=False)),
                ('fec_pago', models.DateTimeField()),
                ('detalle', models.CharField(max_length=45)),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id_proc', models.AutoField(db_column='id_Proc', primary_key=True, serialize=False)),
                ('nom_pro', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'procedimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcedPacien',
            fields=[
                ('idpro_pac', models.AutoField(db_column='idPro_Pac', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('indicacion', models.CharField(max_length=45)),
                ('fec_pro', models.DateTimeField()),
            ],
            options={
                'db_table': 'proced_pacien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_res', models.AutoField(db_column='id_Res', primary_key=True, serialize=False)),
                ('fec_res', models.DateField()),
                ('hora_res', models.TimeField()),
                ('detalle', models.CharField(max_length=45)),
                ('fec_creacion', models.DateTimeField()),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudInsumo',
            fields=[
                ('id_sol_ins', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=45)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'solicitud_insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('idtip_emp', models.AutoField(db_column='idTip_Emp', primary_key=True, serialize=False)),
                ('nom_tp_em', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipPago',
            fields=[
                ('id_tip_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tp_pago', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tip_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpleadoEspecialidad',
            fields=[
                ('empleado_id_emp', models.OneToOneField(db_column='Empleado_id_emp', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='App_mantenedor.empleado')),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'empleado_especialidad',
                'managed': False,
            },
        ),
    ]
