# Generated by Django 4.0.4 on 2022-05-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_mantenedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppClienteContacto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=254)),
                ('tipo_consulta', models.IntegerField()),
                ('mensaje', models.TextField()),
            ],
            options={
                'db_table': 'app_cliente_contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_ser', models.AutoField(primary_key=True, serialize=False)),
                ('nom_serv', models.CharField(max_length=45)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioEmpleado',
            fields=[
                ('idser_emp', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_ser', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'servicio_empleado',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='empleadoespecialidad',
            name='empleado_id_emp',
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.DeleteModel(
            name='EmpleadoEspecialidad',
        ),
    ]
