# Generated by Django 4.0.4 on 2022-06-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_mantenedor', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrsDispo',
            fields=[
                ('idhrs_dispo', models.AutoField(primary_key=True, serialize=False)),
                ('fec_disp', models.DateField(blank=True, null=True)),
                ('hr_disp', models.TimeField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=45, null=True)),
                ('fec_cr', models.DateTimeField(blank=True, null=True)),
                ('prec', models.IntegerField(blank=True, null=True)),
                ('servicio', models.CharField(blank=True, max_length=45, null=True)),
                ('cliente', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('empl', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'hrs_dispo',
                'managed': False,
            },
        ),
    ]
