# Generated by Django 4.0.4 on 2022-06-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_mantenedor', '0004_hrsdispo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrsDispos',
            fields=[
                ('idhrs_dispos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('detalle', models.CharField(max_length=45)),
                ('fec_creacion', models.DateTimeField()),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('horass', models.TimeField()),
            ],
            options={
                'db_table': 'hrs_dispo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_rese', models.AutoField(db_column='id_Res', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('detalle', models.CharField(max_length=45)),
                ('fec_creacion', models.DateTimeField()),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('cliente', models.CharField(max_length=10)),
                ('nom_cliente', models.CharField(max_length=40)),
                ('correo', models.CharField(blank=True, max_length=40, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
    ]
