# Generated by Django 4.0.4 on 2022-06-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_mantenedor', '0005_hrsdispos_reservas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hrsdispos',
            table='hrs_dispos',
        ),
        migrations.AlterModelTable(
            name='reservas',
            table='reservas',
        ),
    ]
