# Generated by Django 4.0.4 on 2022-06-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_mantenedor', '0006_alter_hrsdispos_table_alter_reservas_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('idhrs_dispos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('detalle', models.CharField(max_length=45)),
                ('fec_creacion', models.DateTimeField()),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('horass', models.TimeField()),
            ],
            options={
                'db_table': 'hrs_dispos',
                'managed': False,
            },
        ),
    ]
