# Generated by Django 4.0.4 on 2022-06-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_mantenedor', '0007_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HrsDispos',
        ),
        migrations.DeleteModel(
            name='Reservas',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
